# Generated by Django 5.1.1 on 2024-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='blood_group',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='blood_group',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
