# Generated by Django 5.1.1 on 2024-10-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studentprofile_blood_group_studentprofile_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='permanent_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='present_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
