# Generated by Django 5.1.1 on 2024-10-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_studentprofile_permanent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester'), ('3rd', 'Third Semester'), ('4th', 'Fourth Semester'), ('5th', 'Fifth Semester'), ('6th', 'Sixth Semester'), ('7th', 'Seventh Semester'), ('8th', 'Eighth Semester')], default='1st', max_length=10, null=True),
        ),
    ]
