# Generated by Django 5.1.1 on 2024-10-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentprofile',
            table='student_profiles',
        ),
        migrations.AlterModelTable(
            name='teacherprofile',
            table='teacher_profiles',
        ),
    ]
