# Generated by Django 5.1.2 on 2024-10-14 06:07

import classroom.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='assignments/', validators=[classroom.models.validate_file_type])),
                ('content', models.TextField(null=True)),
                ('semester', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester'), ('3rd', 'Third Semester'), ('4th', 'Fourth Semester'), ('5th', 'Fifth Semester'), ('6th', 'Sixth Semester'), ('7th', 'Seventh Semester'), ('8th', 'Eighth Semester')], default='1st', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('semester', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester'), ('3rd', 'Third Semester'), ('4th', 'Fourth Semester'), ('5th', 'Fifth Semester'), ('6th', 'Sixth Semester'), ('7th', 'Seventh Semester'), ('8th', 'Eighth Semester')], default='1st', max_length=10)),
                ('file', models.FileField(null=True, upload_to='classes/', validators=[classroom.models.validate_video_type])),
                ('link', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='notices/', validators=[classroom.models.validate_file_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester'), ('3rd', 'Third Semester'), ('4th', 'Fourth Semester'), ('5th', 'Fifth Semester'), ('6th', 'Sixth Semester'), ('7th', 'Seventh Semester'), ('8th', 'Eighth Semester')], default='1st', max_length=10)),
                ('file', models.FileField(null=True, upload_to='routines/', validators=[classroom.models.validate_file_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routines',
            },
        ),
    ]
